#!/bin/bash
nsamples=1
sleeptime=0

if ! test -n "$1" || ! test "$1" -gt 0 ; then
	echo >2 "Usage: $0 <pid>"
	exit 1
fi

pid="$1"

for x in $(seq 1 $nsamples)
  do
    quickstack -p $pid
    #gdb -ex "set pagination 0" -ex "thread apply all bt" -batch -p $pid
    sleep $sleeptime
  done | \
awk '
  BEGIN { s = ""; }
  /Thread/ { print s; s = ""; }
  /^\#/ { if ($3 != "in") { $4 = $2 } }
  /^\#/ { if (s != "" ) { s = s "," $4} else { s = $4 } }
  END { print s }
' | sort | uniq -c | sort -r -n -k 1,1
